"""Refactor name to full_name

Revision ID: bd3d2cea4736
Revises: 87eb9ae0da00
Create Date: 2026-04-05 07:36:04.477749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3d2cea4736'
down_revision: Union[str, Sequence[str], None] = '87eb9ae0da00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_superadmin')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
